[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.85
